default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["WEB_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
development:
  <<: *default
  database: flearn_co_api_development
test:
  <<: *default
  database: flearn_co_api_test
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  connect_timeout: 10
  read_timeout: 5
